name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Check with clippy
        run: cargo clippy --all
      - name: Build without features
        run: cargo build --no-default-features
      - name: Build
        run: cargo build --all --verbose
      - name: Run tests
        run: cargo test --all --verbose
